from enum import StrEnum


class Layer(StrEnum):
    RAW_TICKET = "RAW_TICKET"
    THEME_SUMMARY = "THEME_SUMMARY"
    PRD = "PRD"
    ROADMAP = "ROADMAP"


class SourceTool(StrEnum):
    JSM = "JSM"
    CONFLUENCE = "CONFLUENCE"
    JIRA = "JIRA"
    JSON = "JSON"


class AgentRole(StrEnum):
    CUSTOMER = "CUSTOMER"
    SUPPORT_AGENT = "SUPPORT_AGENT"
    SUPPORT_LEAD = "SUPPORT_LEAD"
    PM = "PM"
    AI_ROVO = "AI_ROVO"


class ClaimType(StrEnum):
    PROBLEM = "PROBLEM"
    SOLUTION = "SOLUTION"
    CONSTRAINT = "CONSTRAINT"
    OUTCOME = "OUTCOME"


class EdgeStatus(StrEnum):
    OBSERVED = "OBSERVED"
    INFERRED = "INFERRED"
    HUMAN_CONFIRMED = "HUMAN_CONFIRMED"
    REJECTED = "REJECTED"


class Confidence(StrEnum):
    OBSERVED = "Observed"
    STRONG_INFERENCE = "Strong inference"
    WEAK_INFERENCE = "Weak inference"
    UNRESOLVED = "Unresolved"


class TransformType(StrEnum):
    PRESERVED = "PRESERVED"
    LEGITIMATE_GENERALIZATION = "LEGITIMATE_GENERALIZATION"
    CRITICAL_DETAIL_OMITTED = "CRITICAL_DETAIL_OMITTED"
    SEVERITY_DILUTED = "SEVERITY_DILUTED"
    QUANTITY_CHANGED = "QUANTITY_CHANGED"
    NEGATION_CHANGED = "NEGATION_CHANGED"
    PROBLEM_TO_SOLUTION_SUBSTITUTION = "PROBLEM_TO_SOLUTION_SUBSTITUTION"
    UNSUPPORTED_ADDITION = "UNSUPPORTED_ADDITION"
    CONTRADICTED = "CONTRADICTED"
    NO_EVIDENCE_FOUND = "NO_EVIDENCE_FOUND"


class JobStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class AnalysisStage(StrEnum):
    QUEUED = "QUEUED"
    EXTRACTING_CLAIMS = "EXTRACTING_CLAIMS"
    GENERATING_EMBEDDINGS = "GENERATING_EMBEDDINGS"
    RETRIEVING_EVIDENCE = "RETRIEVING_EVIDENCE"
    CLASSIFYING_EDGES = "CLASSIFYING_EDGES"
    CLASSIFYING_TRANSFORMS = "CLASSIFYING_TRANSFORMS"
    ASSEMBLING_REPORT = "ASSEMBLING_REPORT"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class AnalysisMode(StrEnum):
    HISTORICAL = "HISTORICAL"
    CURRENT = "CURRENT"


class Verdict(StrEnum):
    ALIGNED = "ALIGNED"
    DRIFT = "DRIFT"
    NO_EVIDENCE = "NO_EVIDENCE"
    UNRESOLVED = "UNRESOLVED"
