"""create tier1 schema

Revision ID: 35ac8583490b
Revises: 20260801_0001
Create Date: 2026-08-01 03:37:05.277618
"""
from collections.abc import Sequence

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '35ac8583490b'
down_revision: str | None = '20260801_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_instance', sa.String(length=255), nullable=False),
    sa.Column('source_tool', sa.Enum('JSM', 'CONFLUENCE', 'JIRA', 'JSON', name='source_tool', native_enum=False), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('layer', sa.Enum('RAW_TICKET', 'THEME_SUMMARY', 'PRD', 'ROADMAP', name='artifact_layer', native_enum=False), nullable=False),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts')),
    sa.UniqueConstraint('source_instance', 'source_tool', 'external_id', name='source_identity')
    )
    op.create_index('ix_artifacts_layer', 'artifacts', ['layer'], unique=False)
    op.create_table('artifact_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('author_role', sa.Enum('CUSTOMER', 'SUPPORT_AGENT', 'SUPPORT_LEAD', 'PM', 'AI_ROVO', name='agent_role', native_enum=False), nullable=False),
    sa.Column('source_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_links', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('embedded_with', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(content_hash) = 64', name=op.f('ck_artifact_versions_sha256_hash_length')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_artifact_versions_positive_version_number')),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_artifact_versions_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifact_versions')),
    sa.UniqueConstraint('artifact_id', 'content_hash', name='artifact_hash'),
    sa.UniqueConstraint('artifact_id', 'version_number', name='artifact_version')
    )
    op.create_index(op.f('ix_artifact_versions_artifact_id'), 'artifact_versions', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_artifact_versions_content_hash'), 'artifact_versions', ['content_hash'], unique=False)
    op.create_index('ix_artifact_versions_source_updated_at', 'artifact_versions', ['source_updated_at'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_version_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='job_status', native_enum=False), nullable=False),
    sa.Column('stage', sa.Enum('QUEUED', 'EXTRACTING_CLAIMS', 'GENERATING_EMBEDDINGS', 'RETRIEVING_EVIDENCE', 'CLASSIFYING_EDGES', 'CLASSIFYING_TRANSFORMS', 'ASSEMBLING_REPORT', 'COMPLETED', 'FAILED', name='analysis_stage', native_enum=False), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['decision_version_id'], ['artifact_versions.id'], name=op.f('fk_analysis_jobs_decision_version_id_artifact_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_jobs'))
    )
    op.create_index('ix_analysis_jobs_decision_created', 'analysis_jobs', ['decision_version_id', 'created_at'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_id', sa.String(length=400), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('claim_index', sa.Integer(), nullable=False),
    sa.Column('source_span', sa.Text(), nullable=False),
    sa.Column('span_start', sa.Integer(), nullable=False),
    sa.Column('span_end', sa.Integer(), nullable=False),
    sa.Column('claim_type', sa.Enum('PROBLEM', 'SOLUTION', 'CONSTRAINT', 'OUTCOME', name='claim_type', native_enum=False), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('predicate', sa.Text(), nullable=False),
    sa.Column('object', sa.Text(), nullable=False),
    sa.Column('qualifiers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('claim_index >= 0', name=op.f('ck_claims_nonnegative_claim_index')),
    sa.CheckConstraint('span_end > span_start', name=op.f('ck_claims_valid_span_range')),
    sa.CheckConstraint('span_start >= 0', name=op.f('ck_claims_nonnegative_span_start')),
    sa.ForeignKeyConstraint(['version_id'], ['artifact_versions.id'], name=op.f('fk_claims_version_id_artifact_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims')),
    sa.UniqueConstraint('display_id', name='display_id'),
    sa.UniqueConstraint('version_id', 'claim_index', name='version_claim_index')
    )
    op.create_index(op.f('ix_claims_version_id'), 'claims', ['version_id'], unique=False)
    op.create_table('provenance_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_job_id', sa.UUID(), nullable=False),
    sa.Column('from_version_id', sa.UUID(), nullable=False),
    sa.Column('to_version_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('OBSERVED', 'INFERRED', 'HUMAN_CONFIRMED', 'REJECTED', name='edge_status', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Enum('OBSERVED', 'STRONG_INFERENCE', 'WEAK_INFERENCE', 'UNRESOLVED', name='edge_confidence', native_enum=False), nullable=False),
    sa.Column('evidence_types', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('internal_score', sa.Float(), nullable=False),
    sa.Column('alternatives', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('from_version_id <> to_version_id', name=op.f('ck_provenance_edges_different_versions')),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], name=op.f('fk_provenance_edges_analysis_job_id_analysis_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_version_id'], ['artifact_versions.id'], name=op.f('fk_provenance_edges_from_version_id_artifact_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_version_id'], ['artifact_versions.id'], name=op.f('fk_provenance_edges_to_version_id_artifact_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provenance_edges')),
    sa.UniqueConstraint('analysis_job_id', 'from_version_id', 'to_version_id', name='analysis_edge')
    )
    op.create_index(op.f('ix_provenance_edges_analysis_job_id'), 'provenance_edges', ['analysis_job_id'], unique=False)
    op.create_table('claim_transforms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_job_id', sa.UUID(), nullable=False),
    sa.Column('edge_id', sa.UUID(), nullable=False),
    sa.Column('upstream_claim_id', sa.UUID(), nullable=True),
    sa.Column('downstream_claim_id', sa.UUID(), nullable=True),
    sa.Column('transform_type', sa.Enum('PRESERVED', 'LEGITIMATE_GENERALIZATION', 'CRITICAL_DETAIL_OMITTED', 'SEVERITY_DILUTED', 'QUANTITY_CHANGED', 'NEGATION_CHANGED', 'PROBLEM_TO_SOLUTION_SUBSTITUTION', 'UNSUPPORTED_ADDITION', 'CONTRADICTED', 'NO_EVIDENCE_FOUND', name='transform_type', native_enum=False), nullable=False),
    sa.Column('retained_slots', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('lost_slots', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('introduced_slots', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('upstream_claim_id is not null or downstream_claim_id is not null', name=op.f('ck_claim_transforms_at_least_one_claim')),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], name=op.f('fk_claim_transforms_analysis_job_id_analysis_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['downstream_claim_id'], ['claims.id'], name=op.f('fk_claim_transforms_downstream_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edge_id'], ['provenance_edges.id'], name=op.f('fk_claim_transforms_edge_id_provenance_edges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upstream_claim_id'], ['claims.id'], name=op.f('fk_claim_transforms_upstream_claim_id_claims'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_transforms'))
    )
    op.create_index('ix_claim_transforms_analysis_type', 'claim_transforms', ['analysis_job_id', 'transform_type'], unique=False)
    op.create_index(op.f('ix_claim_transforms_edge_id'), 'claim_transforms', ['edge_id'], unique=False)
    op.create_table('decision_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_job_id', sa.UUID(), nullable=False),
    sa.Column('decision_version_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.Enum('ALIGNED', 'DRIFT', 'NO_EVIDENCE', 'UNRESOLVED', name='report_verdict', native_enum=False), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('max_drift_transform_id', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], name=op.f('fk_decision_reports_analysis_job_id_analysis_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decision_version_id'], ['artifact_versions.id'], name=op.f('fk_decision_reports_decision_version_id_artifact_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['max_drift_transform_id'], ['claim_transforms.id'], name=op.f('fk_decision_reports_max_drift_transform_id_claim_transforms'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_reports')),
    sa.UniqueConstraint('analysis_job_id', name=op.f('uq_decision_reports_analysis_job_id'))
    )
    op.create_index('ix_decision_reports_decision_generated', 'decision_reports', ['decision_version_id', 'generated_at'], unique=False)
    for table_name in (
        'artifacts',
        'artifact_versions',
        'claims',
        'analysis_jobs',
        'provenance_edges',
        'claim_transforms',
        'decision_reports',
    ):
        op.execute(sa.text(f'alter table public.{table_name} enable row level security'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_decision_reports_decision_generated', table_name='decision_reports')
    op.drop_table('decision_reports')
    op.drop_index(op.f('ix_claim_transforms_edge_id'), table_name='claim_transforms')
    op.drop_index('ix_claim_transforms_analysis_type', table_name='claim_transforms')
    op.drop_table('claim_transforms')
    op.drop_index(op.f('ix_provenance_edges_analysis_job_id'), table_name='provenance_edges')
    op.drop_table('provenance_edges')
    op.drop_index(op.f('ix_claims_version_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_analysis_jobs_decision_created', table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index('ix_artifact_versions_source_updated_at', table_name='artifact_versions')
    op.drop_index(op.f('ix_artifact_versions_content_hash'), table_name='artifact_versions')
    op.drop_index(op.f('ix_artifact_versions_artifact_id'), table_name='artifact_versions')
    op.drop_table('artifact_versions')
    op.drop_index('ix_artifacts_layer', table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
